name: Docker Build
on: [push]
env:
  IMAGE_NAME: ${{ github.actor }}/qbittorent-vpn
  REGISTRY: ghcr.io
jobs:
  build-container:
    name: Build and Push container
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Semver run
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        with:
          config_file: ./semver.yaml
          repository_local: true
          repository_url: "https://github.com/${{ github.repository }}"

      - name: Build container
        run: |
          docker build . -t ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }}

      - name: Tag and Push container
        env:
          IMAGE_VERSION: ${{ steps.semver.outputs.semantic_version }}${{ github.ref != 'refs/heads/main' && format('-alpha.{0}-{1}', github.run_number, github.sha ) || '' }}
        run: |
          docker tag ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }} ${{ env.REGISTRY }}/$IMAGE_NAME:$IMAGE_VERSION
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME:$IMAGE_VERSION
      
      - name: Tag and Push container as 'latest'
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }} ${{ env.REGISTRY }}/$IMAGE_NAME:latest
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME:latest