name: Docker Build
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ${{ github.actor }}/qbittorent-vpn
  REGISTRY: ghcr.io
jobs:
  build-container:
    name: Build and Push container
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: |
          docker build . -t ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }}

      - name: Tag and Push container
        env:
          IMAGE_VERSION: v1.0.${{ github.run_number }}
        run: |
          docker tag ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }} ${{ env.REGISTRY }}/$IMAGE_NAME:$IMAGE_VERSION
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME:$IMAGE_VERSION
      
      - name: Tag and Push container as 'latest'
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }} ${{ env.REGISTRY }}/$IMAGE_NAME:latest
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME:latest
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }}
  release:
    needs: [ build-container ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: "update helm chart app version"
        working-directory: ./charts/qbittorrent-vpn
        run: sed -i 's/1.0.0/1.0.0-${{ github.sha }}/g' Chart.yaml
      - name: "update helm chart version"
        working-directory: ./charts/qbittorrent-vpn
        run: sed -i 's/0.0.1/0.0.${{github.run_number}}/g' Chart.yaml        
      - name: "update docker image hash"
        working-directory: ./charts/qbittorrent-vpn
        run: sed -i 's/latest/${{ github.sha }}/g' values.yaml      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"