name: Docker Build
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ${{ github.actor }}/qbittorent-vpn
  REGISTRY: ghcr.io
jobs:
  build-container:
    name: Build and Push container
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: |
          docker build . -t ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }}

      - name: Tag and Push container
        env:
          IMAGE_VERSION: v1.0.${{ github.run_number }}
        run: |
          docker tag ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }} ${{ env.REGISTRY }}/$IMAGE_NAME:$IMAGE_VERSION
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME:$IMAGE_VERSION
      
      - name: Tag and Push container as 'latest'
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ env.REGISTRY }}/$IMAGE_NAME:${{ github.sha }} ${{ env.REGISTRY }}/$IMAGE_NAME:latest
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME:latest